/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-06 01:43:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pacotesviagem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Pc-CaioBarbara/eclipse-workspace-Entrega03/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AgenciaViagem3/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1696877501705L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Pacotes</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- menu principal -->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light bg-light\"\r\n");
      out.write("		style=\"height: 80px;\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"#\"> <img\r\n");
      out.write("				src=\"./assets/images/logo.gif\" alt=\"logo\" class=\"img-fluid\"\r\n");
      out.write("				width=\"100\" height=\"80\">\r\n");
      out.write("			</a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" aria-current=\"page\"\r\n");
      out.write("						href=\"index.html\">Home</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"destino.html\">Destino</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"promocoes.html\">Promoções</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"contato.html\">Contato</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"text-center\">\r\n");
      out.write("		<h3>Pacotes</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=container>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container mt-5 border border-2 border-secondary\">\r\n");
      out.write("			<!-- Botão para abrir o modal de cadastro -->\r\n");
      out.write("			<button type=\"button\" class=\"btn btn-primary mt-3\"\r\n");
      out.write("				data-bs-toggle=\"modal\" data-bs-target=\"#CadastroModal\">Cadastrar</button>\r\n");
      out.write("\r\n");
      out.write("			<!-- Modal de Cadastro -->\r\n");
      out.write("			<div class=\"modal fade\" id=\"CadastroModal\" tabindex=\"-1\"\r\n");
      out.write("				aria-labelledby=\"CadastroModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("				<div class=\"modal-dialog\">\r\n");
      out.write("					<div class=\"modal-content\">\r\n");
      out.write("						<div class=\"modal-header\">\r\n");
      out.write("							<h1 class=\"modal-title fs-5\" id=\"CadastroModalLabel\">Cadastro\r\n");
      out.write("								de Pacotes</h1>\r\n");
      out.write("							<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("								aria-label=\"Close\"></button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"modal-body\">\r\n");
      out.write("							<!-- Formulário de Cadastro -->\r\n");
      out.write("							<form action=\"pacotesviagem-save\">\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"nome_pacote\">Nome do Pacote:</label> <input\r\n");
      out.write("										type=\"text\" class=\"form-control\" id=\"nome_pacote\" name=\"nome\"\r\n");
      out.write("										placeholder=\"Nome do Pacote\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"destino\">Destino:</label> <input type=\"text\"\r\n");
      out.write("										class=\"form-control\" id=\"destino\" name=\"destino\"\r\n");
      out.write("										placeholder=\"Destino\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"preco\">Preço:</label> <input type=\"text\"\r\n");
      out.write("										class=\"form-control\" id=\"preco\" name=\"preco\"\r\n");
      out.write("										placeholder=\"Preço\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"data_partida\">Data de Partida:</label> <input\r\n");
      out.write("										type=\"date\" class=\"form-control\" id=\"data_partida\" name=\"data\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"duracao\">Duração:</label> <input type=\"text\"\r\n");
      out.write("										class=\"form-control\" id=\"duracao\" name=\"duracao\"\r\n");
      out.write("										placeholder=\"Duração\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label for=\"descricao\">Descrição:</label>\r\n");
      out.write("									<textarea class=\"form-control\" id=\"descricao\" name=\"descricao\"\r\n");
      out.write("										placeholder=\"Descrição\"></textarea>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"mt-3\">\r\n");
      out.write("									<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("										data-bs-dismiss=\"modal\">Sair</button>\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-primary\">Salvar</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Tabela de Pacotes de Viagem -->\r\n");
      out.write("			<div class=\"table-responsive\">\r\n");
      out.write("				<table class=\"table\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"col\">Id</th>\r\n");
      out.write("							<th scope=\"col\">Nome Pacote</th>\r\n");
      out.write("							<th scope=\"col\">Preço</th>\r\n");
      out.write("							<th scope=\"col\">Data Partida</th>\r\n");
      out.write("							<th scope=\"col\">Duração</th>\r\n");
      out.write("							<th scope=\"col\">Descrição</th>\r\n");
      out.write("							<th scope=\"col\">Ações</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Rodapé -->\r\n");
      out.write("	<footer class=\"mt-4 bg-primary text-center text-white p-1\">\r\n");
      out.write("		<p>\r\n");
      out.write("			<i class=\"bi bi-c-circle\" style=\"font-size: 1rem\"></i> Todos os\r\n");
      out.write("			direitos reservados à agência de viagens Giramundo.\r\n");
      out.write("		</p>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<!-- Scripts -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("		integrity=\"sha384-KyZXEAg3QhqLMpG8r+O3+XpzrW8p7l2K6n6a4ssYbF4g+pB1z4aO1bN6Lq3qNXdq7\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /pacotesviagem.jsp(130,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/pacotesviagem.jsp(130,6) '${pacotes}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pacotes}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /pacotesviagem.jsp(130,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("pv");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<!-- Linha da tabela preenchida com os dados do pacote -->\r\n");
            out.write("							<tr>\r\n");
            out.write("								<th scope=\"row\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</th>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.nomeDoPacote}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.preco}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.dataDePartida}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.duracao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.descricao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("								<td><a class=\"btn btn-warning\" data-bs-toggle=\"modal\"\r\n");
            out.write("									data-bs-target=\"#AtualizarModal");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Editar</a> <a\r\n");
            out.write("									class=\"btn btn-danger\" data-bs-toggle=\"modal\"\r\n");
            out.write("									data-bs-target=\"#ExcluirModal");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Excluir</a></td>\r\n");
            out.write("							</tr>\r\n");
            out.write("\r\n");
            out.write("							<!-- Modal de Exclusão -->\r\n");
            out.write("							<div class=\"modal fade\" id=\"ExcluirModal");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" tabindex=\"-1\"\r\n");
            out.write("								aria-labelledby=\"ExcluirModalLabel\" aria-hidden=\"true\">\r\n");
            out.write("								<div class=\"modal-dialog\">\r\n");
            out.write("									<div class=\"modal-content\">\r\n");
            out.write("										<div class=\"modal-header\">\r\n");
            out.write("											<h5 class=\"modal-title\">Excluir Pacote</h5>\r\n");
            out.write("											<button type=\"button\" class=\"btn-close\"\r\n");
            out.write("												data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
            out.write("										</div>\r\n");
            out.write("										<div class=\"modal-body\">\r\n");
            out.write("											<p>Atenção! Você está prestes a excluir o pacote.</p>\r\n");
            out.write("										</div>\r\n");
            out.write("										<div class=\"modal-footer\">\r\n");
            out.write("											<button type=\"button\" class=\"btn btn-secondary\"\r\n");
            out.write("												data-bs-dismiss=\"modal\">Sair</button>\r\n");
            out.write("											<a href=\"pacotesviagem-delete?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("												class=\"btn btn-primary\">Excluir</a>\r\n");
            out.write("										</div>\r\n");
            out.write("									</div>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<!-- Modal de Atualização -->\r\n");
            out.write("							<div class=\"modal fade\" id=\"AtualizarModal");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" tabindex=\"-1\"\r\n");
            out.write("								aria-labelledby=\"AtualizarModalLabel\" aria-hidden=\"true\">\r\n");
            out.write("								<div class=\"modal-dialog\">\r\n");
            out.write("									<div class=\"modal-content\">\r\n");
            out.write("										<div class=\"modal-header\">\r\n");
            out.write("											<h1 class=\"modal-title fs-5\" id=\"AtualizarModalLabel\">Atualizar\r\n");
            out.write("												Pacote</h1>\r\n");
            out.write("											<button type=\"button\" class=\"btn-close\"\r\n");
            out.write("												data-bs-dismiss=\"modal\" aria-label=\"close\"></button>\r\n");
            out.write("										</div>\r\n");
            out.write("										<div class=\"modal-body\">\r\n");
            out.write("											<!-- Formulário de Atualização (mesmo código do modal de cadastro) -->\r\n");
            out.write("											<form action=\"pacotesviagem-save\">\r\n");
            out.write("												<div class=\"form-group\">\r\n");
            out.write("													<label for=\"id\">ID:</label> <input type=\"text\"\r\n");
            out.write("														class=\"form-control\" id=\"id\" name=\"id\" placeholder=\"ID\"\r\n");
            out.write("														value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("												</div>\r\n");
            out.write("												<div class=\"form-group\">\r\n");
            out.write("													<label for=\"nome\">Nome Pacote:</label> <input\r\n");
            out.write("														type=\"text\" class=\"form-control\" id=\"nome\"\r\n");
            out.write("														name=\"nome\" placeholder=\"Nome Pacote\"\r\n");
            out.write("														value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.nomeDoPacote}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("												</div>\r\n");
            out.write("												<div class=\"form-group\">\r\n");
            out.write("													<label for=\"destino\">Destino:</label> <input type=\"text\"\r\n");
            out.write("														class=\"form-control\" id=\"destino\" name=\"destino\"\r\n");
            out.write("														placeholder=\"Destino\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.destino}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("												</div>\r\n");
            out.write("												<div class=\"form-group\">\r\n");
            out.write("													<label for=\"preco\">Preço:</label> <input type=\"text\"\r\n");
            out.write("														class=\"form-control\" id=\"preco\" name=\"preco\"\r\n");
            out.write("														placeholder=\"Preço\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.preco}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("												</div>\r\n");
            out.write("												<div class=\"form-group\">\r\n");
            out.write("													<label for=\"data\">Data de Partida:</label> <input\r\n");
            out.write("														type=\"date\" class=\"form-control\" id=\"data\"\r\n");
            out.write("														name=\"data\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.dataDePartida}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("												</div>\r\n");
            out.write("												<div class=\"form-group\">\r\n");
            out.write("													<label for=\"duracao\">Duração:</label> <input type=\"text\"\r\n");
            out.write("														class=\"form-control\" id=\"duracao\" name=\"duracao\"\r\n");
            out.write("														placeholder=\"Duração\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.duracao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("												</div>\r\n");
            out.write("												<div class=\"form-group\">\r\n");
            out.write("													<label for=\"descricao\">Descrição:</label>\r\n");
            out.write("													<textarea class=\"form-control\" id=\"descricao\"\r\n");
            out.write("														name=\"descricao\" placeholder=\"Descrição\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pv.descricao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</textarea>\r\n");
            out.write("												</div>\r\n");
            out.write("\r\n");
            out.write("												<div class=\"mt-3\">\r\n");
            out.write("													<button type=\"button\" class=\"btn btn-secondary\"\r\n");
            out.write("														data-bs-dismiss=\"modal\">Sair</button>\r\n");
            out.write("													<button type=\"submit\" class=\"btn btn-primary\">Salvar</button>\r\n");
            out.write("												</div>\r\n");
            out.write("											</form>\r\n");
            out.write("										</div>\r\n");
            out.write("									</div>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
